### ISSUE TITLE
Installing ipopt

### ISSUE THREAD

**Issue by Beliavsky** [matt-graham/ipopt-fortran-example#1]
Thanks for your project. How do you suggest installing ipopt? Using https://github.com/coin-or/Ipopt ?

**Comment by matt-graham** [comment]
On Ubuntu I've managed to succesfully build the example using a version of Ipopt installed [using `apt`](https://packages.ubuntu.com/search?keywords=coinor-libipopt-dev) and using a [`conda` package](https://anaconda.org/conda-forge/ipopt) (both of these options use MUMPS for the sparse linear solver by default rather than on of the proprietary alternatives). I have added some instructions on setting up the required dependencies and building the example to the `README` file.
